### ISSUE TITLE
Use `fmt::Write` instead of `io::Write` for `generate` and `render`?

### ISSUE THREAD

**Issue by LukasKalbertodt** [cocool97/xml-builder#11]
Hi! I've been wondering whether the data written to the `writer` passed to `generate`/`render` only contains valid UTF8. I couldn't find any documentation, but from briefly looking at the code, it does seem like it? In that case, could one change the trait bound to `fmt::Write`? That would allow passing `String`s to the methods.

I suppose this has something to do with #7?

**Comment by cocool97** [comment]
I understand your concern, but changing from `io::Write` to `fmt::Write` would mean that we couldn't write to a Vec<u8> anymore as this does not implement `fmt::Write`. This would be a breaking change in the API. Couldn't you build the required String from a Vec<u8> using `String::from_utf_8` ?

**Comment by LukasKalbertodt** [comment]
Oh wow, somehow I assumed `Vec` would implement `fmt::Write` as of course `Vec` is perfectly able to contain UTF-8 data. The `Vec -> String` conversion (`String::from_utf_8(vec).unwrap()`) is not as nice (due to the unwrap) as the other way (`string.into_bytes()`). But sure, making a breaking change for this might not be worth it.
