### ISSUE TITLE
What is the license for this software?

### ISSUE THREAD

**Issue by osamu-ikawa** [cocool97/xml-builder#13]
I use this software in my app.

I want to display the appropriate license in my app, but there is no LICENSE file in this repository.

What is the license for this software.  And, who is the copyright holder?

**Comment by cocool97** [comment]
Hey ! 

Glad to hear you're using this library ;) 

It is under `MIT` license, no file is provided as it is stated in `Cargo.toml` and cargo does not like to have both a file and a license-file. Copyright holder is also specified in the `Cargo.toml`.

Let me hear if any information is missing !

**Comment by osamu-ikawa** [comment]
@cocool97 
Thank you.
I could find license and copyright holder in `Cargo.toml`.

> Let me hear if any information is missing !

Based on the history of the repository, should the publication year be 2021-2024?
